title: tnua timing
email: ""
url: http://tnuatiming.com
domain: tnuatiming.com
encoding: "utf-8"
timezone: Asia/Jerusalem
verbose:  true
markdown: kramdown
permalink: /:categories/:year/:title.html
excerpt_separator: <!--more-->
include: [
    english/index.html,
    _*.png,
    _*.svg,
    _*.zip,
    .htaccess
]
exclude: [
    .tt,
    id_rsa,
    id_rsa.pub,
    english/index201*.html,
    images/temp,
    images/original,
    images/old,
    live/Images_old,
    live*/elite.js,
    results/index_*.html,
    results/index201*.html,
    _includes/*_old*, 
    style/*_old*,
    feed.xml, 
    about,
    .git,
    .gitignore,
    .directory,
    CNAME,
    svg-icons,
    svg-decorations,
    scss,
    .sass-cache,
    package.json,
    package-lock.json,
    Gruntfile.js,
    Guardfile,
    Gemfile,
    Gemfile.lock,
    node_modules,
    sitemap.xml.old,
    .grunt,
    .ftpauth,
    gitup.sh,
    gitup_descr.sh,
    convert_html_to_csv*,
    readme.md,
    lftp.log,
    log/
]

