title: tnua timing
email: ""
url: http://tnuatiming.com
domain: tnuatiming.com
encoding: "utf-8"
timezone: Asia/Jerusalem
markdown: rdiscount
permalink: /:categories/:year/:title.html
excerpt_separator: <!--more-->
include: [
    live/Images/,
    english/index.html,
    .htaccess
]
exclude: [
  images/temp,
  images/original,
  images/old,
  live/Images_old,
  results/index_*.html,
  results/index201*.html,
  _includes/*_old*, 
  style/*_old*,
  feed.xml, 
  about,
  .git,
  .gitignore,
  .directory,
  CNAME,
  svg-icons,
  svg-decorations,
  scss,
  .sass-cache,
  package.json,
  package-lock.json,
  Gruntfile.js,
  Guardfile,
  Gemfile,
  Gemfile.lock,
  node_modules,
  sitemap.xml.old,
  .grunt,
  gitup.sh,
  gitup_descr.sh,
  readme.md
]

