title: tnua timing
email: tnuatiming@domain.com
url: "http://tnuatiming.com"
encoding:     "utf-8"
markdown: rdiscount
permalink: /:categories/:year/:title.html
include: [
    english/index.html,
    live/index.html,
    .htaccess
]
exclude: [
  images/temp,
  images/original,
  results/index_*.html,
  feed.xml, 
  about,
  .git,
  .gitignore,
  .directory,
  CNAME,
  svg-icons,
  svg-decorations,
  scss,
  .sass-cache,
  package.json, 
  Gruntfile.js,
  Guardfile,
  Gemfile,
  Gemfile.lock,
  node_modules,
  sitemap.xml.old,
  .ftpauth,
  .ftppass,
  readme.md
]

excerpt_separator: <!--more-->